[package]
name = "omniscience_typst"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]


[dependencies]
wasm-minimal-protocol="0.1.0"
omni = { path = "../lib"}
toml.workspace = true
serde.workspace = true
spin = "0.10.0"
