[package]
name = "lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
camino.workspace = true
tokio = { version = "1.48.0", features = ["full"] } # TODO: reduce features
tower-lsp-server = "0.23.0"
omni = { path = "../lib" }
